### PR TITLE
 Set Up Database Configuration With Flyway

### LINKED ISSUE #5: Database: Set Up Database Infrastructure
Set up the initial database using MySQL or another chosen database system. Create the necessary configurations and environments for local development.

### PR DESCRIPTION
**Pull request by AhmedMohamedAbdelaty**
closes #5 

**Description:**
- Configured PostgreSQL as the database for the application.
- Integrated **Flyway** for database migration management.
- Added initial migration scripts for schema setup.
- Updated the README file to include instructions for setting up the database with Docker.

### CODE REVIEW

**Review by AhmedYahia74 — APPROVED** [review]

**Review by AhmedFatthy1040 — DISMISSED** [review]

**Comment by AhmedFatthy1040** [comment]
I tried building the project, but the build is failing on my machine. Could you please let me know the following details?

1.     Java version you are using.
2.     Spring Boot version.
3.     Gradle version.

**Comment by AhmedFatthy1040** [comment]
I've checked my setup, and I'm currently using Gradle 4.4.1 and Java 23.

**Comment by AhmedMohamedAbdelaty** [comment]
Use Java 21 instead; see `languageVersion = JavaLanguageVersion.of(21)` in `build.gradle`.

We can edit it to use 23, but let's stick with 21 for compatibility.

**Review by AhmedYahia74 — APPROVED** [review]

**Review by AhmedFatthy1040 — APPROVED** [review]

**Pull request merged**
